/*
This file is part of Ext JS 4.2

Copyright (c) 2011-2015 Sencha Inc

Contact:  http://www.sencha.com/contact

Commercial Usage
Licensees holding valid commercial licenses may use this file in accordance with the Commercial
Software License Agreement provided with the Software or, alternatively, in accordance with the
terms contained in a written agreement between you and Sencha.

If you are unsure which license is appropriate for your use, please contact the sales department
at http://www.sencha.com/contact.

Build date: 2015-07-29 13:28:30 (5d04230422a2a93197a6ac72739567d59f2539a4)
*/

/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../../../extjs/src",
  "Ext.AbstractComponent": "../../../../platform/src/AbstractComponent.js",
  "Ext.AbstractManager": "../../../../platform/src/AbstractManager.js",
  "Ext.AbstractPlugin": "../../../../platform/src/AbstractPlugin.js",
  "Ext.Ajax": "../../../../platform/src/Ajax.js",
  "Ext.Array": "../../../../platform/core/src/lang/Array.js",
  "Ext.Base": "../../../../platform/core/src/class/Base.js",
  "Ext.Class": "../../../../platform/core/src/class/Class.js",
  "Ext.ClassManager": "../../../../platform/core/src/class/ClassManager.js",
  "Ext.ComponentLoader": "../../../../platform/src/ComponentLoader.js",
  "Ext.ComponentManager": "../../../../platform/src/ComponentManager.js",
  "Ext.ComponentQuery": "../../../../platform/src/ComponentQuery.js",
  "Ext.Date": "../../../../platform/core/src/lang/Date.js",
  "Ext.DomHelper": "../../../../extjs/src/dom/Helper.js",
  "Ext.DomQuery": "../../../../extjs/src/dom/Query.js",
  "Ext.ElementLoader": "../../../../platform/src/ElementLoader.js",
  "Ext.Error": "../../../../platform/core/src/lang/Error.js",
  "Ext.EventManager": "../../../../platform/core/src/EventManager.js",
  "Ext.EventObject": "../../../../platform/core/src/EventObject.js",
  "Ext.EventObjectImpl": "../../../../platform/core/src/EventObject.js",
  "Ext.Function": "../../../../platform/core/src/lang/Function.js",
  "Ext.JSON": "../../../../platform/core/src/misc/JSON.js",
  "Ext.Loader": "../../../../platform/core/src/class/Loader.js",
  "Ext.ModelManager": "../../../../platform/src/ModelManager.js",
  "Ext.Msg": "../../../../extjs/src/window/MessageBox.js",
  "Ext.Number": "../../../../platform/core/src/lang/Number.js",
  "Ext.Object": "../../../../platform/core/src/lang/Object.js",
  "Ext.PluginManager": "../../../../platform/src/PluginManager.js",
  "Ext.Queryable": "../../../../platform/src/Queryable.js",
  "Ext.String": "../../../../platform/core/src/lang/String.js",
  "Ext.Supports": "../../../../platform/core/src/Support.js",
  "Ext.Template": "../../../../platform/src/Template.js",
  "Ext.Version": "../../../../platform/core/src/version/Version.js",
  "Ext.XTemplate": "../../../../platform/src/XTemplate.js",
  "Ext.XTemplateCompiler": "../../../../platform/src/XTemplateCompiler.js",
  "Ext.XTemplateParser": "../../../../platform/src/XTemplateParser.js",
  "Ext.chart": "../../../../platform/src/chart",
  "Ext.container.AbstractContainer": "../../../../platform/src/container/AbstractContainer.js",
  "Ext.container.DockingContainer": "../../../../platform/src/container/DockingContainer.js",
  "Ext.core.DomHelper": "../../../../extjs/src/dom/Helper.js",
  "Ext.core.DomQuery": "../../../../extjs/src/dom/Query.js",
  "Ext.data": "../../../../platform/src/data",
  "Ext.diag": "../../../../platform/src/diag",
  "Ext.direct": "../../../../platform/src/direct",
  "Ext.dom.AbstractElement": "../../../../platform/core/src/dom/AbstractElement.js",
  "Ext.dom.AbstractElement_insertion": "../../../../platform/core/src/dom/AbstractElement_insertion.js",
  "Ext.dom.AbstractElement_static": "../../../../platform/core/src/dom/AbstractElement_static.js",
  "Ext.dom.AbstractElement_style": "../../../../platform/core/src/dom/AbstractElement_style.js",
  "Ext.dom.AbstractElement_traversal": "../../../../platform/core/src/dom/AbstractElement_traversal.js",
  "Ext.dom.AbstractHelper": "../../../../platform/core/src/dom/AbstractHelper.js",
  "Ext.dom.AbstractQuery": "../../../../platform/core/src/dom/AbstractQuery.js",
  "Ext.dom.CompositeElement": "../../../../platform/core/src/dom/CompositeElement.js",
  "Ext.dom.CompositeElementLite": "../../../../platform/core/src/dom/CompositeElementLite.js",
  "Ext.draw": "../../../../platform/src/draw",
  "Ext.env": "../../../../platform/core/src/env",
  "Ext.fx": "../../../../platform/src/fx",
  "Ext.layout.ClassList": "../../../../platform/src/layout/ClassList.js",
  "Ext.layout.Context": "../../../../platform/src/layout/Context.js",
  "Ext.layout.ContextItem": "../../../../platform/src/layout/ContextItem.js",
  "Ext.layout.Layout": "../../../../platform/src/layout/Layout.js",
  "Ext.layout.SizeModel": "../../../../platform/src/layout/SizeModel.js",
  "Ext.layout.SizePolicy": "../../../../platform/src/layout/SizePolicy.js",
  "Ext.layout.component.Auto": "../../../../platform/src/layout/component/Auto.js",
  "Ext.layout.component.Component": "../../../../platform/src/layout/component/Component.js",
  "Ext.layout.component.Draw": "../../../../platform/src/layout/component/Draw.js",
  "Ext.layout.container.Auto": "../../../../platform/src/layout/container/Auto.js",
  "Ext.panel.AbstractPanel": "../../../../platform/src/panel/AbstractPanel.js",
  "Ext.perf": "../../../../platform/core/src/perf",
  "Ext.rtl.AbstractComponent": "../../../../platform/src/rtl/AbstractComponent.js",
  "Ext.rtl.EventObjectImpl": "../../../../platform/src/rtl/EventObjectImpl.js",
  "Ext.rtl.chart": "../../../../platform/src/rtl/chart",
  "Ext.rtl.draw": "../../../../platform/src/rtl/draw",
  "Ext.rtl.util": "../../../../platform/src/rtl/util",
  "Ext.rtl.util.Floating": "../../../../extjs/src/rtl/util/Floating.js",
  "Ext.selection.DataViewModel": "../../../../platform/src/selection/DataViewModel.js",
  "Ext.selection.Model": "../../../../platform/src/selection/Model.js",
  "Ext.state": "../../../../platform/src/state",
  "Ext.util.AbstractMixedCollection": "../../../../platform/src/util/AbstractMixedCollection.js",
  "Ext.util.Bindable": "../../../../platform/src/util/Bindable.js",
  "Ext.util.DelayedTask": "../../../../platform/core/src/util/DelayedTask.js",
  "Ext.util.ElementContainer": "../../../../platform/src/util/ElementContainer.js",
  "Ext.util.Event": "../../../../platform/core/src/util/Event.js",
  "Ext.util.Filter": "../../../../platform/src/util/Filter.js",
  "Ext.util.Format": "../../../../platform/core/src/util/Format.js",
  "Ext.util.Grouper": "../../../../platform/src/util/Grouper.js",
  "Ext.util.HashMap": "../../../../platform/src/util/HashMap.js",
  "Ext.util.Inflector": "../../../../platform/src/util/Inflector.js",
  "Ext.util.LocalStorage": "../../../../platform/src/util/LocalStorage.js",
  "Ext.util.LruCache": "../../../../platform/src/util/LruCache.js",
  "Ext.util.Memento": "../../../../platform/src/util/Memento.js",
  "Ext.util.MixedCollection": "../../../../platform/src/util/MixedCollection.js",
  "Ext.util.Observable": "../../../../platform/src/util/Observable.js",
  "Ext.util.Offset": "../../../../platform/src/util/Offset.js",
  "Ext.util.Point": "../../../../platform/src/util/Point.js",
  "Ext.util.Positionable": "../../../../platform/core/src/util/Positionable.js",
  "Ext.util.ProtoElement": "../../../../platform/src/util/ProtoElement.js",
  "Ext.util.Queue": "../../../../platform/src/util/Queue.js",
  "Ext.util.Region": "../../../../platform/src/util/Region.js",
  "Ext.util.Renderable": "../../../../platform/src/util/Renderable.js",
  "Ext.util.Sortable": "../../../../platform/src/util/Sortable.js",
  "Ext.util.Sorter": "../../../../platform/src/util/Sorter.js",
  "Ext.util.TaskManager": "../../../../platform/core/src/util/TaskManager.js",
  "Ext.util.TaskRunner": "../../../../platform/core/src/util/TaskRunner.js",
  "Ext.view.AbstractView": "../../../../platform/src/view/AbstractView.js",
  "ExtThemeNeptune": "../../overrides"
});
Ext.ClassManager.addNameAlternateMappings({
  "ExtThemeNeptune.Component": [],
  "ExtThemeNeptune.container.ButtonGroup": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.grid.column.RowNumberer": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "ExtThemeNeptune.menu.Menu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "ExtThemeNeptune.panel.Panel": [],
  "ExtThemeNeptune.panel.Table": [],
  "ExtThemeNeptune.panel.Tool": [],
  "ExtThemeNeptune.picker.Month": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "ExtThemeNeptune.tab.Tab": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "ExtThemeNeptune.toolbar.Toolbar": []
});
Ext.ClassManager.addNameAliasMappings({
  "ExtThemeNeptune.Component": [],
  "ExtThemeNeptune.container.ButtonGroup": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.grid.column.RowNumberer": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "ExtThemeNeptune.menu.Menu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "ExtThemeNeptune.panel.Panel": [],
  "ExtThemeNeptune.panel.Table": [],
  "ExtThemeNeptune.panel.Tool": [],
  "ExtThemeNeptune.picker.Month": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "ExtThemeNeptune.tab.Tab": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "ExtThemeNeptune.toolbar.Toolbar": []
});
Ext.Loader.loadScript("../../overrides/Component.js");
Ext.Loader.loadScript("../../overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../../overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../../overrides/panel/Panel.js");
Ext.Loader.loadScript("../../overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../../overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../../overrides/picker/Month.js");
Ext.Loader.loadScript("../../overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../../overrides/panel/Table.js");
Ext.Loader.loadScript("../../overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../../overrides/grid/column/RowNumberer.js");
Ext.Loader.loadScript("../../overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../../overrides/menu/Separator.js");
Ext.Loader.loadScript("../../overrides/menu/Menu.js");
Ext.Loader.loadScript("../../overrides/panel/Tool.js");
Ext.Loader.loadScript("../../overrides/tab/Tab.js");
